spring.application.name=backend

# conexão com o banco H2(em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true